Repository intel-retail/rtsf-at-checkout-reference-design, pull requests merged in 2023-10, with the labels that each got.

#71 feat: Update Portainer to use ce image
  loss-detection-app/docker-compose.portainer.yml
Labels: enhancement, dependencies

#73 feat(device_mqtt, device_rest): migrate device-list files for device-…
  loss-detection-app/res/device-mqtt/devices/device-list.toml
  loss-detection-app/res/device-mqtt/devices/device-list.yaml
  loss-detection-app/res/device-rest/devices/device-list.toml
  loss-detection-app/res/device-rest/devices/device-list.yaml
Labels: enhancement

#82 feat(device-scale): Migrate device-scale device service to EdgeX v3.0
  loss-detection-app/docker-compose.edgex.yml
  loss-detection-app/docker-compose.loss-detection.yml
  rtsf-at-checkout-device-scale/Dockerfile
  rtsf-at-checkout-device-scale/cmd/main.go
  rtsf-at-checkout-device-scale/cmd/res/configuration.toml
  rtsf-at-checkout-device-scale/cmd/res/configuration.yaml
  rtsf-at-checkout-device-scale/cmd/res/devices/device-list.toml
  rtsf-at-checkout-device-scale/cmd/res/devices/device-list.yaml
  rtsf-at-checkout-device-scale/driver/scaleDevice.go
  rtsf-at-checkout-device-scale/driver/scaleDevice_test.go
  rtsf-at-checkout-device-scale/driver/scaleDriver.go
  rtsf-at-checkout-device-scale/driver/scaleDriver_test.go
  rtsf-at-checkout-device-scale/go.mod
  rtsf-at-checkout-device-scale/go.sum
Labels: enhancement, dependencies

#88 feat(event-reconciler): migrate Event Reconciler to App SDK 3.0.1
  loss-detection-app/docker-compose.loss-detection.yml
  rtsf-at-checkout-event-reconciler/Dockerfile
  rtsf-at-checkout-event-reconciler/config/configuration.go
  rtsf-at-checkout-event-reconciler/events/demo_setup.go
  rtsf-at-checkout-event-reconciler/events/event_order.go
  rtsf-at-checkout-event-reconciler/events/helper_functions_test.go
  rtsf-at-checkout-event-reconciler/events/pim_lookup.go
  rtsf-at-checkout-event-reconciler/events/process_events.go
  rtsf-at-checkout-event-reconciler/events/process_events_test.go
  rtsf-at-checkout-event-reconciler/events/region_of_interest.go
  rtsf-at-checkout-event-reconciler/go.mod
  rtsf-at-checkout-event-reconciler/go.sum
  rtsf-at-checkout-event-reconciler/main.go
  rtsf-at-checkout-event-reconciler/res/configuration.toml
  rtsf-at-checkout-event-reconciler/res/configuration.yaml
Labels: enhancement, dependencies, go

#83 feat: Update loss detection compose file to remove env variables not needed any more.
  loss-detection-app/docker-compose.loss-detection.yml
Labels: enhancement

#87 feat(loss detector): migrate loss-detector to App SDK 3.0.1
  loss-detection-app/docker-compose.loss-detection.yml
  rtsf-at-checkout-loss-detector/Dockerfile
  rtsf-at-checkout-loss-detector/functions/notify.go
  rtsf-at-checkout-loss-detector/go.mod
  rtsf-at-checkout-loss-detector/go.sum
  rtsf-at-checkout-loss-detector/main.go
  rtsf-at-checkout-loss-detector/res/configuration.toml
  rtsf-at-checkout-loss-detector/res/configuration.yaml
Labels: enhancement, dependencies, go

#92 fix: Centralize docker networks
  Makefile
  loss-detection-app/docker-compose.edgex.yml
  loss-detection-app/docker-compose.loss-detection.yml
  loss-detection-app/docker-compose.vap.yml
  rtsf-at-checkout-cv-region-of-interest/src/enterexit.py
Labels: enhancement, dependencies
